image: Visual Studio 2017

configuration:
  - Debug
  - Release

install:
  - git submodule update --init --recursive

build_script:
  - mkdir build
  - cd build
  - cmake -T v141_xp ..
  - cmake --build . --config %CONFIGURATION%

artifacts:
  - path: build\$(CONFIGURATION)\client.dll
